ALTER TABLE Chapter  WITH CHECK ADD  CONSTRAINT FK_Chapter_Volume FOREIGN KEY(VolumeID)
    REFERENCES Volume (ID)
    
ALTER TABLE Chapter CHECK CONSTRAINT FK_Chapter_Volume
    
ALTER TABLE ChapterMark  WITH CHECK ADD  CONSTRAINT FK_ChapterMark_Chapter FOREIGN KEY(ChapterID)
    REFERENCES Chapter (ID)
    
ALTER TABLE ChapterMark CHECK CONSTRAINT FK_ChapterMark_Chapter
    
ALTER TABLE ChapterMark  WITH CHECK ADD  CONSTRAINT FK_ChapterMark_User FOREIGN KEY(UserID)
    REFERENCES User (ID)
    
ALTER TABLE ChapterMark CHECK CONSTRAINT FK_ChapterMark_User
    
ALTER TABLE Comment  WITH CHECK ADD  CONSTRAINT FK_comment_comment1 FOREIGN KEY(ParentID)
    REFERENCES Comment (ID)
    
ALTER TABLE Comment CHECK CONSTRAINT FK_comment_comment1
    
ALTER TABLE Comment  WITH CHECK ADD  CONSTRAINT FK_comment_User FOREIGN KEY(OwnerID)
    REFERENCES User (ID)
    
ALTER TABLE Comment CHECK CONSTRAINT FK_comment_User
    
ALTER TABLE CommentReport  WITH CHECK ADD  CONSTRAINT FK_CommentReport_comment FOREIGN KEY(CommentID)
    REFERENCES Comment (ID)
    
ALTER TABLE CommentReport CHECK CONSTRAINT FK_CommentReport_comment
    
ALTER TABLE CommentReport  WITH CHECK ADD  CONSTRAINT FK_CommentReport_User FOREIGN KEY(ReporterID)
    REFERENCES User (ID)
    
ALTER TABLE CommentReport CHECK CONSTRAINT FK_CommentReport_User
    
ALTER TABLE Notification  WITH CHECK ADD  CONSTRAINT FK_Notification_User FOREIGN KEY(User_ID)
    REFERENCES User (ID)
    
ALTER TABLE Notification CHECK CONSTRAINT FK_Notification_User
    
ALTER TABLE NovelGenre  WITH CHECK ADD  CONSTRAINT FK_NovelGenre_Genre FOREIGN KEY(GenreID)
    REFERENCES Genre (ID)
    
ALTER TABLE NovelGenre CHECK CONSTRAINT FK_NovelGenre_Genre
    
ALTER TABLE NovelGenre  WITH CHECK ADD  CONSTRAINT FK_NovelGenre_Novel FOREIGN KEY(NovelID)
    REFERENCES Novel (ID)
    
ALTER TABLE NovelGenre CHECK CONSTRAINT FK_NovelGenre_Novel
    
ALTER TABLE NovelReport  WITH CHECK ADD  CONSTRAINT FK_NovelReport_Novel FOREIGN KEY(NovelID)
    REFERENCES Novel (ID)
    
ALTER TABLE NovelReport CHECK CONSTRAINT FK_NovelReport_Novel
    
ALTER TABLE NovelReport  WITH CHECK ADD  CONSTRAINT FK_NovelReport_User FOREIGN KEY(ReporterID)
    REFERENCES User (ID)
    
ALTER TABLE NovelReport CHECK CONSTRAINT FK_NovelReport_User
    
ALTER TABLE Restriction  WITH CHECK ADD  CONSTRAINT FK_Restriction_User FOREIGN KEY(ExecutorID)
    REFERENCES User (ID)
    
ALTER TABLE Restriction CHECK CONSTRAINT FK_Restriction_User
    
ALTER TABLE Restriction  WITH CHECK ADD  CONSTRAINT FK_Restriction_User1 FOREIGN KEY(RestrictedUserID)
    REFERENCES User (ID)
    
ALTER TABLE Restriction CHECK CONSTRAINT FK_Restriction_User1
      
ALTER TABLE UserToken  WITH CHECK ADD  CONSTRAINT FK_UserToken_User FOREIGN KEY(UserID)
    REFERENCES User (ID)
    
ALTER TABLE UserToken CHECK CONSTRAINT FK_UserToken_User
    
ALTER TABLE Volume  WITH CHECK ADD  CONSTRAINT FK_Volume_Novel FOREIGN KEY(NovelID)
    REFERENCES Novel (ID)
    
ALTER TABLE Volume CHECK CONSTRAINT FK_Volume_Novel
